# Generated by Django 4.2.14 on 2024-08-04 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 13, 21, 57, 973061)),
            preserve_default=False,
        ),
    ]
