# Generated by Django 4.2.14 on 2024-09-28 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("group_composition_id", models.BigIntegerField()),
                (
                    "creator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_group",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message", models.CharField(max_length=512)),
                ("date", models.DateTimeField()),
                ("chat_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatting.chatgroup")),
            ],
            options={
                "db_table": "chat_message",
            },
        ),
        migrations.CreateModel(
            name="UserMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_read", models.BooleanField(default=False)),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatting.chatmessage")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "user_message",
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="receivers",
            field=models.ManyToManyField(
                related_name="receivers", through="chatting.UserMessage", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="sender", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ChatGroupUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatting.chatgroup")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "chat_group_user",
            },
        ),
        migrations.AddField(
            model_name="chatgroup",
            name="users",
            field=models.ManyToManyField(
                related_name="users", through="chatting.ChatGroupUser", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
