# Generated by Django 4.2.14 on 2024-10-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to=""),
        ),
    ]
