# Generated by Django 4.2.14 on 2024-10-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0002_chatmessage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="image",
            field=models.ImageField(default=None, null=True, upload_to="message_pictures"),
        ),
    ]
