# Generated by Django 4.2.14 on 2024-10-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not Started'), ('Running', 'Running'), ('Finished', 'Finished')], max_length=16),
        ),
        migrations.CreateModel(
            name='TournamentGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.UUIDField(default=None, null=True)),
                ('end_date', models.DateField()),
                ('game_type', models.CharField(choices=[('Elimination', 'Elimination'), ('Seeding', 'Seeding')], max_length=32)),
                ('round_number', models.IntegerField(default=None, null=True)),
                ('round', models.IntegerField(default=None, null=True)),
                ('is_dummy', models.BooleanField(default=False)),
                ('player1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_game',
            },
        ),
    ]
