# Generated by Django 4.2.14 on 2024-10-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_status_tournamentgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('Single elimination', 'Single Elimination')], max_length=64),
        ),
        migrations.AlterField(
            model_name='tournamentgame',
            name='game_type',
            field=models.CharField(choices=[('Elimination', 'Elimination'), ('Normal', 'Normal')], max_length=32),
        ),
        migrations.CreateModel(
            name='TournamentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy', models.ImageField(default='default_prize.png', upload_to='tournament_prizes')),
                ('participant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentparticipant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'db_table': 'tournament_prize',
            },
        ),
    ]
