# Generated by Django 5.1 on 2024-08-11 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_time', models.DateTimeField(default=None, null=True)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_asker', to=settings.AUTH_USER_MODEL)),
                ('challenger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_challenger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'challenges',
            },
        ),
        migrations.CreateModel(
            name='MatchRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('actual_time', models.DateTimeField(default=None, null=True)),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mask_asker', to=settings.AUTH_USER_MODEL)),
                ('challenger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mask_challenger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_requests',
            },
        ),
    ]
